name: Deploy calculator app in EKS Cluster
on:
  workflow_dispatch:
  push:
    branches:
      - feature/eks-deploy
env:
  CLUSTER_NAME: testcluster
  REGION: ap-south-1
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
jobs:
  deploy-eks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Update Kubeconfig 
        run: aws eks update-kubeconfig --region ${REGION} --name ${CLUSTER_NAME}

      - name: Set Kubeconfig
        run: KUBE_CONFIG=$(cat ~/.kube/config | base64)
      