name: Deploy calculator app in EKS Cluster
on:
  workflow_dispatch:
  push:
    branches:
      - feature/eks-deploy
env:
  CLUSTER_NAME: testcluster
  REGION: ap-south-1
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
jobs:
  deploy-eks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Get Pod details
        uses: ianbelcher/eks-kubectl-action@master
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          args: get pods
      